### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by justjulez420** [dillongoostudios/goo-blender#2]
I've tried a couple ways to build this on Arch Linux but can't get it to work. Installing requirements.txt and following the official blender build instructions resulted in a broken build with missing icons that crashes when switching to shaded view.

Is there anything else i need to do? I'll not even pretend to know what i'm doing, but just for reference i tried building regular blender 3.3 and it worked fine.

Here is my CMakeError.log:

> Performing C++ SOURCE FILE Test SUPPORT_NEON_BUILD failed with the following output:
Change Dir: /home/julez/github/goo-blender/build_linux/CMakeFiles/CMakeTmp
Run Build Command(s):/usr/bin/make -f Makefile cmTC_9c5ec/fast && make[1]: Entering directory '/home/julez/github/goo-blender/build_linux/CMakeFiles/CMakeTmp'
/usr/bin/make  -f CMakeFiles/cmTC_9c5ec.dir/build.make CMakeFiles/cmTC_9c5ec.dir/build
make[2]: Entering directory '/home/julez/github/goo-blender/build_linux/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_9c5ec.dir/src.cxx.o
/usr/bin/c++ -DSUPPORT_NEON_BUILD   -o CMakeFiles/cmTC_9c5ec.dir/src.cxx.o -c /home/julez/github/goo-blender/build_linux/CMakeFiles/CMakeTmp/src.cxx
/home/julez/github/goo-blender/build_linux/CMakeFiles/CMakeTmp/src.cxx:1:10: fatal error: arm_neon.h: No such file or directory
    1 | #include <arm_neon.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/cmTC_9c5ec.dir/build.make:78: CMakeFiles/cmTC_9c5ec.dir/src.cxx.o] Error 1
make[2]: Leaving directory '/home/julez/github/goo-blender/build_linux/CMakeFiles/CMakeTmp'
make[1]: *** [Makefile:127: cmTC_9c5ec/fast] Error 2
make[1]: Leaving directory '/home/julez/github/goo-blender/build_linux/CMakeFiles/CMakeTmp'
Source file was:
#include <arm_neon.h>
       int main() {return vaddvq_s32(vdupq_n_s32(1));}

**Comment by justjulez420** [comment]
Update: I've got the missing icon's fixed by using the release/datafiles/locale folder from the regular blender source code, but it's still crashing when entering any eevee-viewport. 
running it from the terminal throws this at me when entering shaded view:

> ERROR (gpu.shader): GPU_material_compile VertShader:
      |
 4473 |
      |  ^
      | Error: #extension directive is not allowed in the middle of a shader
ERROR (gpu.shader): GPU_material_compile FragShader:
      |
 4804 |
      |  ^
      | Error: #extension directive is not allowed in the middle of a shader
ERROR (gpu.shader): GPU_material_compile VertShader:
      |
 4483 |
      |  ^
      | Error: #extension directive is not allowed in the middle of a shader
ERROR (gpu.shader): GPU_material_compile FragShader:
      |
 4814 |
      |  ^
      | Error: #extension directive is not allowed in the middle of a shader

any ideas?

**Comment by Imhungreee** [comment]
I'm trying to build it as well. Fingers crossed...

**Comment by justjulez420** [comment]
Sooo, here is how i got it to build without errors on arch linux:

- clone goo-blender
- run 'pip install -r requirements.txt'
- copy the content of the release/datafiles/locale folder from blenders regular source code to goo-blender
- run 'make update'
- for me, make update complained about not being able to access goo-blender-addons, so i cloned it manually and put it in release/scripts/addons
- run 'make'

but it still crashes when entering any eevee-viewport. however, google made me feel like this is a different error related to mesa graphics drivers or something like that and has nothing to do with my build so i should probably open a new issue for that.

@Imhungreee was your build successful? and if so, which operating system did you use?

**Comment by sodiufas** [comment]
Can't build with MSVS 2022, should I get 2019 instead maybe? I'm dumb..

**Comment by sodiufas** [comment]
C:\work\lib\win64_vc15\tbb\include\tbb/parallel_sort.h(125,1): warning C4180: qualifier applied to function type has no meaning; ignored [c:\work\build_windows_x64_vc17_Release\source\blender\gpencil_modifiers\bf_gpencil_modifiers.vcxproj]
C:\work\lib\win64_vc15\tbb\include\tbb/parallel_sort.h(128): warning C4180: qualifier applied to function type has no meaning; ignored [c:\work\build_windows_x64_vc17_Release\source\blender\gpencil_modifiers\bf_gpencil_modifiers.vcxproj]
C:\work\lib\win64_vc15\tbb\include\tbb/parallel_sort.h(128,1): warning C4180: qualifier applied to function type has no meaning; ignored [c:\work\build_windows_x64_vc17_Release\source\blender\gpencil_modifiers\bf_gpencil_modifiers.vcxproj]
C:\work\lib\win64_vc15\tbb\include\tbb/parallel_sort.h(102,1): warning C4180: qualifier applied to function type has no meaning; ignored [c:\work\build_windows_x64_vc17_Release\source\blender\gpencil_modifiers\bf_gpencil_modifiers.vcxproj]
C:\work\lib\win64_vc15\tbb\include\tbb/parallel_sort.h(106): warning C4180: qualifier applied to function type has no meaning; ignored [c:\work\build_windows_x64_vc17_Release\source\blender\gpencil_modifiers\bf_gpencil_modifiers.vcxproj]
C:\work\lib\win64_vc15\tbb\include\tbb/parallel_sort.h(106,1): warning C4180: qualifier applied to function type has no meaning; ignored [c:\work\build_windows_x64_vc17_Release\source\blender\gpencil_modifiers\bf_gpencil_modifiers.vcxproj]
C:\work\goo\source\blender\imbuf\intern\jp2.c(19,10): fatal  error C1083: Cannot open include file: 'openjpeg.h': No such file or directory [c:\work\build_windows_x64_vc17_Release\source\blender\imbuf\bf_imbuf.vcxproj]
CUSTOMBUILD : error : malformed object name HEAD [c:\work\build_windows_x64_vc17_Release\source\creator\buildinfo.vcxproj]
CUSTOMBUILD : error : malformed object name HEAD [c:\work\build_windows_x64_vc17_Release\source\creator\buildinfo.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\work\build_windows_x64_vc17_Release\CMakeFiles\4344fa0e91989eb937284c275c97e1d7\buildinfo.h_fake.rule;C:\work\build_windows_x64_vc17_Release\CMakeFiles\b563a0e3b844fe16d4ee0fede2d3e489\buildinfo.rule;C:\work\goo\source\creator\CMakeLists.txt' exited with code -1. [c:\work\build_windows_x64_vc17_Release\source\creator\buildinfo.vcxproj]
    6 Warning(s)
    4 Error(s)

Time Elapsed 00:24:12.42

**Comment by Floreum** [comment]
For me it kept failing on building the .dll files so I just grabbed the ones from my vanilla 3.3 install and put them into the half-compiled Goo build and now it works.

```
   -- Installing: J:/blender-git/build_windows_x64_vc17_Release/bin/Release/3.3/datafiles/fonts/NotoSansThai-VariableFont_wdth,wght.woff2
  CMake Error at source/creator/cmake_install.cmake:48 (file):
    file INSTALL cannot find
    "J:/blender-git/goo-blender/release/datafiles/locale/languages": File
    exists.
  Call Stack (most recent call first):
    cmake_install.cmake:104 (include)


C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: The command "setlocal [J:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: "C:\Program Files (x86)\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake [J:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd [J:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: :cmEnd [J:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [J:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: :cmErrorLevel [J:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: exit /b %1 [J:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: :cmDone [J:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd [J:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(159,5): error MSB3073: :VCEnd" exited with code 1. [J:\blender-git\build_windows_x64_vc17_Release\INSTALL.vcxproj]
Error during install phase
```

**Comment by m3t4f1v3** [comment]
> copy the content of the release/datafiles/locale folder from blenders regular source code to goo-blender
> for me, make update complained about not being able to access goo-blender-addons, so i cloned it manually and put it in release/scripts/addons

git submodule update --init --recursive does this for you

**Comment by SerenoV7** [comment]
I'm getting an error while building on Windows.
```
LINK : fatal error LNK1181: cannot open input file 'X:\goo-blender\..\lib\win64_vc15\opencollada\lib\opencollada\xml.li
b' [X:\build_windows_x64_vc17_Release\source\creator\blender.vcxproj]
```

**Comment by Artemis-chan** [comment]
make sure to run `make update` before building

**Comment by justjulez420** [comment]
I just rebuild and everything seems fixed now, so i'll close this

**Comment by legendboyAni** [comment]
Guys if you still have this issue here is what i did and to me it seems working properly but i didn't test this completely (and ofc you need python git git-lfs)
- clone goo-engine repo
- cd into goo-engine
- run this `./build_files/build_environment/install_linux_packages.py`
- then download the libraries by running this `./build_files/utils/make_update.py --use-linux-libraries`
- then do not do make update
- first delete the goo-engine folder where bcz we need to git clone it again bcz make_update.py f*cks up the goo-engine
- then git clone the goo-engine again
- now just run make don't do make update
and there is also 2 more problem i faced, to fixed them do this
- go out of the goo-engine folder where you can see a lib folder go into it
- then linux_x86_64_glibc_228 and there you will find a webp named folder change it's name to libwebp
- and go back to goo-engine folder then source/creator
- open the buildinfo.c into your text editor
- add these too lines there
int TIFFFaxBlackCodes;
int TIFFFaxWhiteCodes;
![image](https://github.com/dillongoostudios/goo-engine/assets/115929231/8bc738d4-9b3b-4e1a-9f41-7ba4512b32eb)

- then run make
after build test if everything is working or not, and if you guys don't wanna do this all i made an Appimage of it after building, i can share it if you want.

**Comment by ikoshura** [comment]
>       if you guys don't wanna do this all i made an Appimage of it after building, i can share it if you want.
Hey, thank you very much for the guide. It runs perfectly when I tested it in Deepin Linux 23 RC (Debian-based), but now I'm having problems doing it in Nobara OS (Fedora-based). I've been trying to install it for 2 days using various methods, and still cannot install it. If you don't mind, could you share the AppImage, please? I wanted to try it in Nobara because it's my daily driver for now. Thank you.

**Comment by flumpsi** [comment]
please do
